name: cpp study test action
on: [push]
jobs:
  Test-Job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: echo "start action"
      - run: pwd
      - run: ls -al
